#1059 Test SqlConnectOptions creation from URL
hibernate/hibernate-reactive pull request #1135
Opened 2022-01-18 14:47 UTC by blafond

See #1059

Changed `DefaultSqlClientPoolConfiguration.connectOptions()` to parse URI using vertx sql client `SqlConnectOptions.fromUri()`

Note that vertx parsing logic currently recognizes a limited set of URI parameters which was logged with this issue: [#1115 ](https://github.com/eclipse-vertx/vertx-sql-client/issues/1115).  The conversation currently stands with adding a logged warning message for each non-supported parameter.

2022-01-18 16:11 UTC, DavideD commented
Thanks, I have to finish something else but I will review this soon

2022-01-19 18:00 UTC, DavideD requested changes
I haven't checked the test case but there are several things that don't seem right.
I will have a look at the tests tomorrow.

2022-01-19 22:03 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ReactiveToVertxUriConverter.java
> +		else if ( uri.toString().contains( "cockroachdb" ) ) {
good catch.

2022-01-19 22:03 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ReactiveToVertxUriConverter.java
> +		}
done

2022-01-24 14:48 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ReactiveToVertxUriConverter.java
> +			String rawQuery = uri.getRawQuery();
fixed

2022-01-24 14:49 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ReactiveToVertxUriConverter.java
> +		if ( scheme.equals( "db2" ) && database.indexOf( ':' ) > 0 ) {
fixed

2022-01-24 14:51 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ReactiveToVertxUriConverter.java
> + * Vertx JDBC URI parsers expect a PostgreSQL-like structure which is not neccessarily
fixed

2022-01-24 14:51 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java
> +                    "database username not specified (set the property 'javax.persistence.jdbc.user', or include it as a parameter in the connection URL)" );
done

2022-01-24 14:51 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ReactiveToVertxUriConverter.java
> +	 * @return uri
done

2022-01-24 14:52 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ReactiveToVertxUriConverter.java
> +			}
done

2022-01-24 14:52 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ReactiveToVertxUriConverter.java
> +		if ( scheme.equals( "db2" ) && database.indexOf( ':' ) > 0 ) {
fixed

2022-01-24 14:56 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java
> +                ( originalScheme.equalsIgnoreCase( "cockroachdb" ) && connectOptions.getPort() == 5432 ) ) {
fixed

2022-01-24 15:01 UTC, blafond commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java
> +            connectOptions.setPassword( user );
fixed

2022-02-25 14:15 UTC, DavideD commented
I think I'm going to close this PR. I'm not convinced about this approach anymore. It seems that converting the JDBC url to a vert.x one still requires a similar amount of work to what we have now.
I think I prefer what we do  now.

2022-02-25 14:15 UTC, closed without merging