Improve error message when lazy collection is not initialized
hibernate/hibernate-reactive pull request #1323
Opened 2022-06-02 16:24 UTC by blafond

fixes #1205

2022-06-02 16:32 UTC, gavinking commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
> +	@Message(id = 56, value = "Collection cannot be initialized: %1$s\nFetch the connection by using Mutiny.fetch, Stage.fetch or use `fetch join` in your query")
But I would definitely avoid backticks there. Oh and "collection", not "connection".

How about:

    fetch the collection using 'Mutiny.fetch', 'Stage.fetch' or 'fetch join' in HQL

2022-06-02 19:44 UTC, gavinking commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
> +	@Message(id = 56, value = "Collection cannot be initialized: %1$s\nFetch the connection by using Mutiny.fetch, Stage.fetch or use `fetch join` in your query")
Excellent thanks 🙏

2022-06-03 13:48 UTC, DavideD requested changes
Thanks!
The error message looks good but I don't think we need the additional test cases for fetching associations. We already test fetching for the different type of associations elsewhere and these classes test  that we throw the right error message when a lazy initialization error occurs.

I would prefer to keep them simpler. Unless you think that a specific use case isn't covered by our test suit.

2022-06-03 14:19 UTC, blafond commented
Looking through our tests, we don't have many that have entities with uninitialized `List<..>` or `Set<>` and they don't test this use-case.

There's only a 2 that use `Stage.fetch()`  (collection is initialized) and none that use `Mutiny.fetch()`

These new tests cover all scenarios in one class.

2022-06-03 14:37 UTC, DavideD commented
> There's only a 2 that use Stage.fetch() (collection is initialized) and none that use Mutiny.fetch() 

? 

I haven't checked each single use case but these are all the classes  testing Mutiny.fetch:

* LazyOrderedElementCollectionForEmbeddableTypeListTest
* ManyToManyMapTest
* ManyToManySetTest
* ManyToManyTest
* NonNullableManyToOneTest
* OneToManyMapTest
* OneToManySetTest
* OneToManyTest
* OrderedEmbeddableCollectionTest
* OrderedManyToManyTest
* OrderedOneToManyTestMutiny
* SubselectElementCollectionForEmbeddableTypeListTest

And these are the test classes for `Stage.fetch`:

* BatchFetchTest
* CascadeComplicatedTest
* CascadeComplicatedToOnesEagerTest
* CascadeTest
* EagerUniqueKeyTest
* FilterTest
* LazyManyToOneAssociationTest
* LazyOneToManyAssociationWithFetchTest
* LazyUniqueKeyTest
* OrphanRemovalTest
* SubselectFetchTest

What's different between the additional tests and the ones in 
`LazyOneToManyAssociationWithFetchTest` and `OneToManyTest`?

Also, the additional tests don't need to be in the same commit you are using to update the log message. It would be nice to have them in a separate  commit (they are not related to this fix).

2022-06-06 14:09 UTC, blafond commented
Most of the tests that use fetch for collections have entities that are initialized in the entity definition (i.e. new ArrayList<...> , new HashSet<...>) or define instances of the collection via custom constructor etc.

If it's important to have a test that has a true NULL array definition and the collection is initialized internally then I think adding these tests with versions of `fetch` methodology makes sense.

2022-06-09 11:11 UTC, merged