[#1714] Fixes for deprecated classes/methods
hibernate/hibernate-reactive pull request #1715
Opened 2023-07-21 14:21 UTC by blafond

2023-07-21 15:53 UTC, blafond commented
@sebersole Reactive still contains a few deprecated situations. One is in [ReactiveInsertCoordinator](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveInsertCoordinator.java), which extends [InsertCoordinator](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinator.java )

Are there any methods available using the new EntityMappingType/AttributeMapping framework to replace the deprecated calls?  (i.e. `getEntityMetamodel().isDynamicInsert() `, `entityMetamodel.hasPreInsertGeneratedValues() `, `entityMetamodel.getGenerators()`)

2023-07-24 09:02 UTC, DavideD commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityUpdateAction.java
> +	protected void handleDeleted(EntityEntry entry, EntityPersister persister, Object instance) {
The comment is not about making this method protected, it's about making the method in ORM protected so that we can remove this code from Reactive

2023-07-24 09:05 UTC, DavideD requested changes
Revert back all the comments with the TODO, please.
They are there to remind use the changes we need in ORM.

2023-07-24 09:05 UTC, DavideD commented on hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityUpdateAction.java
> +	protected void handleNaturalIdResolutions(EntityPersister persister, SharedSessionContractImplementor session, Object id) {
All the TODO that you have removed are about making the method in ORM protected, so that we can remove them from Hibernate Reactive

2023-08-29 16:24 UTC, blafond commented
ORM merged this PR:  https://github.com/hibernate/hibernate-orm/pull/7079

So visibility of methods have been fixed in ORM.

2023-10-02 12:26 UTC, closed without merging