Tests to check for BatchingConnection if batch size > 1
hibernate/hibernate-reactive pull request #925
Opened 2021-08-02 20:05 UTC by blafond

Tests to support [#877](https://github.com/hibernate/hibernate-reactive/issues/877)

2021-08-02 20:26 UTC, gavinking commented
Hrm, @blafond I was really hoping to not add `unwrap()` methods to our public API. JPA has them because there are multiple vendor implementations, but we don't have that need here.

2021-08-02 20:26 UTC, gavinking commented
Hrm, @blafond I was really hoping to not add `unwrap()` methods to our public API. JPA has them because there are multiple vendor implementations, but we don't have that need here.

2021-08-02 20:46 UTC, blafond commented
The `ReactiveSessionImpl.unwrap()` isn't available on our `Mutiny.Session` or `Stage.Session` interfaces and are not directly available in our tests. Not sure how to pull that info out of a `ReactiveSession` without going through those interfaces.

.. and I do agree... seems a little heavy change just to perform a test.

2021-08-02 21:31 UTC, gavinking commented
Yeah, well, right, and this is exactly why I didn't add tests for this when I fixed the bug.

So an alternative, I suppose, would be to typecast to ``MutinySessionImpl`, and get the connection from there.

2021-08-02 21:45 UTC, blafond commented
that would work but require accessing the `delegate` session to get the `delegate.getReactiveConnection()`

Would there be a future need/benefit to implementing a `ReactiveConnection` enum to apply to **Proxy, Batching and SqlClient** connection types and add a simple `ReactiveSession.getConnectionType()` method?

2021-08-02 21:50 UTC, gavinking commented
> that would work but require accessing the `delegate` session to get the `delegate.getReactiveConnection()`

Right. I think it's fine to expose the `delegate` on the `XxxxImpl` classes, just for this particular test.

> Would there be a future need/benefit to implementing a `ReactiveConnection` enum to apply to **Proxy, Batching and SqlClient** connection types and add a simple `ReactiveSession.getConnectionType()` method?

I mean that just seems like too much extra code, and I'm not sure how it would ever be useful to the _user_.

2021-08-03 14:35 UTC, blafond commented
removed the api changes and added a `getReactiveConnection()` method which pulls from the `delegate` reactive session.

2021-08-03 14:45 UTC, DavideD commented
I think you've squashed your fix over the last commit upstream

2021-08-03 14:48 UTC, blafond commented
yes :(  I'm going to revert and recommit correctly

2021-08-03 15:20 UTC, DavideD reviewed
There are a couple of very minor things but otherwise I think we can merge this

2021-08-03 15:20 UTC, DavideD commented on hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
> +	public void testBatchingConnection(TestContext context) {
I don't think you need the parameter for this test because nothing is reactive

2021-08-03 15:20 UTC, DavideD commented on hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
> +	public void testBatchingConnectionMutiny(TestContext context) {
I don't think you need the parameter for this test because nothing is reactive

2021-08-03 15:20 UTC, DavideD commented on hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
> +		Assertions.assertThat(((MutinySessionImpl)session).getReactiveConnection()).isInstanceOf( BatchingConnection.class );
Not critical, but you can create an import static of `Assertions.assertThat`

2021-08-03 18:33 UTC, DavideD requested changes

2021-08-03 18:33 UTC, DavideD commented on hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
> +		Stage.Session session = getSessionFactory().openSession();
Sorry, one thing I've just noticed... You are not using the method `openSession` in the superclass, meaning that the session doesn't get closed at the end of the test.

2021-08-03 18:33 UTC, DavideD commented on hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
> +		Mutiny.Session session = getMutinySessionFactory().openSession();
You are not using the method `openMutinySession` in the superclass, meaning that the session doesn't get closed at the end of the test.

2021-08-03 19:05 UTC, gavinking commented
LGTM now.

2021-08-03 19:05 UTC, gavinking commented
LGTM now.

2021-08-03 19:36 UTC, blafond commented
I added try/finally to insure session close is called.

2021-08-03 19:48 UTC, merged